### ISSUE TITLE
Why do we have two `bash -c` when starting instance server?

### ISSUE THREAD

**Issue by camelop** [CoLearn-Dev/colink-sdk-python-dev#37]
https://github.com/CoLearn-Dev/colink-sdk-python-dev/blob/3da50791dd5f790c4d5bae54f30c11a48301b1fc/colink/instant_server.py#L20-L22

in fact, why do we have two `bash -c` above?

_Originally posted by @camelop in https://github.com/CoLearn-Dev/colink-sdk-python-dev/pull/33#discussion_r1110909083_

**Comment by quwenjie** [comment]
I tested using only one `bash -c`. It will lead to the error: `FileNotFoundError: [Errno 2] No such file or directory: 'bash -c "$(curl -fsSL https://raw.githubusercontent.com/CoLearn-Dev/colinkctl/main/install_colink.sh)"'`.
