### ISSUE TITLE
CI workflow exceed time

### ISSUE THREAD

**Issue by quwenjie** [CoLearn-Dev/colink-sdk-python-dev#43]
This probabilistically happens: all tests of `pytest` passes, but after that `pytest` gets stuck, and eventually runs out of time, the reason is unclear up to now. An example is here: https://github.com/CoLearn-Dev/colink-sdk-python-dev/actions/runs/4310787672/jobs/7519567197

**Comment by camelop** [comment]
Also notes from @quwenjie : "the test won't run completely" might be because of p2p retry
